### ISSUE TITLE
CG_World, No collision after last update?

### ISSUE THREAD

**Issue by FrozenRune** [midgen/cashgenUE#12]
Hi.
I noticed that you have updated the CG_World branch with collision. But I'm not getting any collision even with the Collision Enabled checked. Even in a fresh project, everything compiles and no errors given. There are still no collision.

**Comment by FrozenRune** [comment]
CookCollisionNow() was the solution it seems.
Unless there is some other way to do it using multithreading?

**Comment by midgen** [comment]
Collision cooking is heavily embedded in the engine, not possible to get it off the game thread in a plugin at the moment.
