### ISSUE TITLE
Question about last steps in README

### ISSUE THREAD

**Issue by victorbstan** [midgen/cashgenUE#15]
Thanks for providing this plugin, it's helping me get up to speed with some UE features.

I have a question about the last two steps in the setup in README:

```
    5. Open the project, and add a CGTerrainManager.
    6. On the beginplay event, call the SetupTerrain method.
```

I have a C++ game mode, and I have an override for the `BeginPlay()` method:

```
#include "CashGen/TerrainManager.h"

void AProcTerrainC2GameModeBase::BeginPlay()
{
	Super::BeginPlay();

	SetupTerrain();
}
```

First off, the `include` is wrong, but I'm not sure how to include something from a plugin, the plugin content doesn't seem to be visible in my VisualStudio project.

Second, this SetupTerrain call, I have a feeling your instructions might be talking about calling it in a Blueprint... is there a way to do this all in C++? I'm really trying to avoid Blueprints as much as possible. If you could help me figure this out I'd appreciate it!

**Comment by victorbstan** [comment]
I figured out that I had to re-build the solution from within Unreal Engine for VisualStudio to pick up on `#include "CGTerrainManager.h"` as a real thing, but `SetUpTerrain();` is still not a thing...

**Comment by midgen** [comment]
The method is ACGTerrainManager::SetupTerrain, you need to call it on an instance of CGTerrainManager.

**Comment by victorbstan** [comment]
Thanks, although it seems I have to provide it with a number of different parameters, which isn't explained in the README.

**Comment by midgen** [comment]
I'm nearly finished with the multiplayer branch and will be merging to master in the next couple of days. This should hopefully be the last significant API change.

The code steps should be simpler, just one step:

1. Call SetupTerrainGenerator with the various struct attributes/noise generators

Any Actors that you have given a TerrainTrackerComponent to will take care of registering themselves with the ACGTerrain actor.

fyi - You can't just new an AActor, you have to use World::SpawnActor

**Comment by midgen** [comment]
See the latest README.md

https://github.com/midgen/cashgenUE
