### ISSUE TITLE
How to use this plugin in 4.17? And can't get plugin content in 4.16

### ISSUE THREAD

**Issue by liu0fanyi** [midgen/cashgenUE#17]
I can find RMC plugin just in 4.16.....

And I try to use this plugin in 4.16, But I can't get the plugin content, I check the open content view, And I get the plugin content folder, but there is nothing...

I try to move uassets under plugin content directly to my content folder...still nothing show in my UE4 Editor...

Any help?
Thanks a lot!

**Comment by midgen** [comment]
Make sure you use the 4.16 branch if you're on 4.16.

https://github.com/midgen/cashgenUE/tree/4.16

I've been away on vacation, but do plan on doing a new setup tutorial video soon!
