### ISSUE TITLE
Missing CGMeshdata.generated.h

### ISSUE THREAD

**Issue by speedpacer** [midgen/cashgenUE#18]
Everything is fine on my Windows client but when I try to build on a Linux dedicated server, I get the following error: 

UnrealBuildTool: ERROR: System.IO.FileNotFoundException: Could not find file "/.../Plugins/cashgenUE/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/CashGen/CGMeshdata.generated.h"

This is CentOS 7, clang 3.5 and UE 4.17.1

**Comment by midgen** [comment]
Going to need some more information than this, or I'll close. Thanks.

**Comment by speedpacer** [comment]
This was a while ago and I haven't tried it since then.  I'll take another stab at it when I get home.
