### ISSUE TITLE
The tile the player stands on is empty

### ISSUE THREAD

**Issue by Streliteela** [midgen/cashgenUE#19]
Awesome work and thanks a lot for sharing.

I have a problem when using this plugin to explore a large map :(
I add a CGTerrainTrackerComponent to the default player (ThirdPersonCharacter), the tile the player stands on is always empty and will be filled until the player leaves it.
![image](https://user-images.githubusercontent.com/13235660/31888204-a87457e4-b82d-11e7-81d3-6529fc274b30.png)
![image](https://user-images.githubusercontent.com/13235660/31888207-b00d6afe-b82d-11e7-9902-a72c07b589c9.png)
While if I add a CGTerrainTrackerComponent to the default gamemode, it will be empty all the time. 

Could you tell me how to fix this? ( I post a reply aobut this on the Unreal Engine Forums.)
Any suggestion is appreciated :-)

**Comment by midgen** [comment]
It's possible you're spawning inside the tile. Trying making sure your player start is above the terrain, and/or use some code to place the player on the terrain surface when it's complete.

**Comment by midgen** [comment]
Going to close this as I have no repro and suspect it's a configuration issue. Let me know if you need any assistance.

**Comment by Streliteela** [comment]
Sorry for the late reply and thanks a lot for the update.  I'll try it and give a feedback as soon as possible  since  I am focusing on another project now. Maybe you can close this issue first. Thanks :+1:
