### ISSUE TITLE
Collision in packaged version

### ISSUE THREAD

**Issue by lievends** [midgen/cashgenUE#27]
Hi,
I am using your plugin in a project, it's absolutely great ;-)
In the editor, everything works perfectly, but once packaged, there seems something wrong with collision (or LOD) calculation.
The terrain part which is calculated at startup is running fine, but once the player get further in the world, it looks like the map is redrawn, and the player falls through the world.
I even have this when packaging you demo project.
Any ideas ?

**Comment by fblah** [comment]
Hi,
I am experiencing a similar problem. Were you able to fix it?

**Comment by lievends** [comment]
Finally found a solution ;-)
Someone on the unreal forum found it to be a bug in UE4, not handling nested structs correctly in packaged versions.
The solution is to set MakeCGTerrainConfig node manually.
https://forums.unrealengine.com/community/work-in-progress/81996-cashgen-kinda-infinite-procedural-world-generator?p=1625716#post1625716
