### ISSUE TITLE
Event OnTerrainComplete

### ISSUE THREAD

**Issue by Ahleroy** [midgen/cashgenUE#32]
Hello,

I want to start an actor moving when the initial terrain is complete. I try to access to the event OnTerrainComplete() of the CGTerrainManager from the actor ticking function (C++) but with no success. How would you do such as thing ?

It might be import to notice that my actor isn't the actor whose the CGTerrainTracker is attached to.

Many thanks,

**Comment by midgen** [comment]
If you look at CGTerrainTrackerComponent.cpp:69, you'll see where the component binds to the event. You can do the same wherever you like, but you'll need to get the reference to the terrain manager first.

`				MyTerrainManager->OnTerrainComplete().AddUObject(this, &UCGTerrainTrackerComponent::OnTerrainComplete);`
