### ISSUE TITLE
4.17 not work cannot Compile

### ISSUE THREAD

**Issue by mengdada** [midgen/cashgenUE#35]
![image](https://user-images.githubusercontent.com/5186863/54292273-d6cd0380-45e8-11e9-888c-8f3a8f39b250.png)
![FA90SBSLF$Z59_B1@J}YKBG](https://user-images.githubusercontent.com/5186863/54292304-e3515c00-45e8-11e9-895d-2226b3376c3f.png)
![6B%_F@3YACF S1 HLKALJI](https://user-images.githubusercontent.com/5186863/54292340-fbc17680-45e8-11e9-8847-baacd97cca03.png)

cashGen can not compile,I do not know why？ this is the log.

Module.CashGen.cpp
C:\Users\lianghongjun\Desktop\RuntimeMeshComponent-Examples-master\Plugins\cashgenUE-4.17\Source\CashGen\Private\CGTerrainGeneratorWorker.cpp(312): error C2039: ??SetNormalAndTangent??: ???ǡ?FRuntimeMeshVertexSimple???ĳ?Ա
c:\users\lianghongjun\desktop\runtimemeshcomponent-examples-master\plugins\runtimemeshcomponent-master\source\runtimemeshcomponent\public\RuntimeMeshGenericVertex.h(718): note: ?μ???FRuntimeMeshVertexSimple????????
C:\Users\lianghongjun\Desktop\RuntimeMeshComponent-Examples-master\Plugins\cashgenUE-4.17\Source\CashGen\Private\CGTile.cpp(113): error C2039: ??bShouldSerializeMeshData??: ???ǡ?URuntimeMeshComponent???ĳ?Ա
C:\Users\lianghongjun\Desktop\RuntimeMeshComponent-Examples-master\Plugins\RuntimeMeshComponent-master\Source\RuntimeMeshComponent\Public\RuntimeMeshComponent.h(17): note: ?μ???URuntimeMeshComponent????????
C:\Users\lianghongjun\Desktop\RuntimeMeshComponent-Examples-master\Plugins\cashgenUE-4.17\Source\CashGen\Private\CGWorldFace.cpp(25): error C2039: ??bShouldSerializeMeshData??: ???ǡ?URuntimeMeshComponent???ĳ?Ա
C:\Users\lianghongjun\Desktop\RuntimeMeshComponent-Examples-master\Plugins\cashgenUE-4.17\Source\CashGen\Public\CGWorld.h(8): note: ?μ???URuntimeMeshComponent????????
ERROR: UBT ERROR: Failed to produce item: C:\Users\lianghongjun\Desktop\RuntimeMeshComponent-Examples-master\Plugins\cashgenUE-4.17\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor-CashGen.lib
Total build time: 19.58 seconds (Local executor: 0.00 seconds)
LogInit: Warning: Still incompatible or missing module: UE4Editor-CashGen.dll
LogExit: Preparing to exit.
LogModuleManager: Shutting down and abandoning module DesktopPlatform (38)
LogModuleManager: Shutting down and abandoning module AnimationModifiers (36)
LogModuleManager: Shutting down and abandoning module PropertyEditor (35)
LogModuleManager: Shutting down and abandoning module AudioEditor (32)
LogModuleManager: Shutting down and abandoning module TextureCompressor (30)
LogModuleManager: Shutting down and abandoning module ShaderCore (28)
LogModuleManager: Shutting down and abandoning module Landscape (26)
LogModuleManager: Shutting down and abandoning module SlateRHIRenderer (24)
LogModuleManager: Shutting down and abandoning module OpenGLDrv (22)
LogModuleManager: Shutting down and abandoning module D3D11RHI (20)
LogModuleManager: Shutting down and abandoning module AnimGraphRuntime (18)
LogModuleManager: Shutting down and abandoning module Renderer (16)
LogModuleManager: Shutting down and abandoning module Engine (14)
LogModuleManager: Shutting down and abandoning module CoreUObject (12)
LogModuleManager: Shutting down and abandoning module NetworkFile (10)
LogModuleManager: Shutting down and abandoning module CookedIterativeFile (8)
LogModuleManager: Shutting down and abandoning module StreamingFile (6)
LogModuleManager: Shutting down and abandoning module SandboxFile (4)
LogModuleManager: Shutting down and abandoning module PakFile (2)
LogExit: Exiting.

**Comment by midgen** [comment]
You'll need to use a 4.17 compatible version of the Runtime Mesh Component, it should work with the 4.17 branch version of CashGen. 

Beyond that, I'm sorry I don't have the spare time to support very old versions at the moment!
