### ISSUE TITLE
Default LoadingPhase causing editor to "forget" all CG-elements

### ISSUE THREAD

**Issue by sfla** [midgen/cashgenUE#37]
Added a CGTerrainTracker as component to a characterBP. The next time I restart Unreal Engine + my project, I get an error saying it couldn't find the module (or something). When I go back into the characterBP, the CGTerrainTracker is completely missing.
I tried setting the CGTerrainTracker directly by blueprint (Add CGTerrain Tracker Component) directly after Event BeginPlay, which works, but the next time I restart the project, the component in the dashboard is "empty", and only named "Add Component", sayin ERROR. Every knowledge of CG is lost.

It seemed like the entire Unreal application didn't know that cashgen existed at initialization, so I googled to see if I could affect the order of initialization of plugins. I found the enum ELoadingPhase. 

I just opened the CashGen.uplugin and changed "LoadingPhase": "Default" to "LoadingPhase":"PostConfigInit". This fixed everything.

I have no idea how to do pull requests etc, so.. here I am.

But if there is a better way to solve this, e.g if there is a priority/order-list of plugins, please let me know:)

**Comment by prom123** [comment]
Just change "LoadingPhase": "Default" to "LoadingPhase": "PreDefault" in the CashGen.uplugin file...

**Comment by midgen** [comment]
Submitted 

a35bbcb4049c094626d6be47fe16f1f03297ed92
