### ISSUE TITLE
How to Spawn Foliage

### ISSUE THREAD

**Issue by smessmer** [midgen/cashgenUE#38]
I'm currently trying to learn UE4 and found this amazing project. Thank you very much for publishing it :)

I saw some of your videos online where you also spawned foliage into the world, but I couldn't figure out how to do that. The procedural foliage spawner from the Kite Open World Demo in UE4 doesn't seem to work with the generated terrain as it complains about not finding a surface to put foliage on. Did you write a spawner yourself? Is it published somewhere?

**Comment by midgen** [comment]
There was a system I dabbled with a long time ago on the project but never got to a standard I was really happy with. I'm unlikely to get around to adding it again any time soon I'm afraid.
