### ISSUE TITLE
Refactor to support RuntimeMeshComponent v4.0

### ISSUE THREAD

**Issue by midgen** [midgen/cashgenUE#52]
The updated RMC has significant changes to the mesh data structures that are going to need a decent amount of refactoring work.

**Comment by DanielDylan** [comment]
What are you plans and schedule on this?  Any progress?  Can I help you with this?

**Comment by midgen** [comment]
Plans are all a bit up in the air at the moment! I will need to try and find some time for this but I'm making sure I get away from the computer after I finish work hours for now.

The RMC was basically re-written so CashgenUE needs a major refactor to accommodate it. You are more than welcome to work on a PR...I will try and get into a routine where I spend some time on it.
________________________________

**Comment by midgen** [comment]
I decided as I'm not actively developing this plugin anymore, I'm just going to revert to using the ProceduralMeshComponent that comes with the engine. It's too much work to maintain both the engine and RMC dependencies.

This has been submitted. 

81429932f93cf8782e46ef375d6e6bd66974ea14
