### ISSUE TITLE
Need help for install

### ISSUE THREAD

**Issue by bootlegbaby** [midgen/cashgenUE#7]
Getting this warning when try open editor.

'Missing or incompatible modules in OceanPlugin plugin - would you like to disable it? You will no longer be able to open any assets created using it.'

When I press 'Yes', get this message and editor crushes.
'Plugin 'OceanPlugin' failed to load because module 'OceanPlugin' could not be found. Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project.'

What should I do for this?

**Comment by midgen** [comment]
What UnrealEngine version are you trying it on? The master branch is on 4.14.

If you're trying 4.15 preview you'll need to have a look at finding an up to date version of the OceanPlugin. Otherwise, just remove the ocean from the project, save, and then remove OceanPlugin entirely.

**Comment by bootlegbaby** [comment]
Thanks for the help, editor runs when delete OceanPlugin folder. Version is 4.14.3.

Now I stuck at the popup window says 'cashgenUE could not be compiled, Try rebuilding from source manually.'

How can I do that?

**Comment by krojew** [comment]
I'm having the exact same issue for 4.15 with latest master for plugin.

**Comment by midgen** [comment]
I'm looking into these packaging issues and working on cleaning up the samples. I'll be removing the OceanPlugin assets as it's not maintained and concentrate on the core plugin.
