### ISSUE TITLE
Unreal can't load cashgen

### ISSUE THREAD

**Issue by davidg0** [midgen/cashgenUE#9]
I put cashgen, runtime mesh component and unreal fast noise under the plugin folder, modified the plugin file of cashgen by setting "enabled by default" trye, and added the dependencies in the build.cs file. Unreal says that cashgen cannot be loaded because of an unknown error.
I'm using unreal 4.15.3.

**Comment by kenwi** [comment]
Still having problems? I'm using 4.16.2.

**Comment by midgen** [comment]
Pretty generic error I'm afraid. I put up some walkthrough videos a while back that show how to set everything up. Excuse the terrible audio!

https://m.youtube.com/watch?v=gv2lpnUm4xE

**Comment by midgen** [comment]
No further response. Closing issue.
